import { Inter } from "next/font/google";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

const noto_sans = Noto_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "NPTEL Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#e9f2fa] ${noto_sans.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
